config/routes.rb
Rails.application.routes.draw do
  namespace :listings do
    resources :reports, only: %i[index show new create]
    resources :pets, only: %i[new create show]
    resources :completed, only: :show
    resources :posts, only: :index
  end

  devise_for :users
  resources :about, only: :index
  resources :contact, only: %i[index create]

  root 'home#index'
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_one :pet, dependent: :destroy

  enum :listing_type, { lost: 0, found: 1 }, default: 0

  def self.search(params)
    return all unless params.present?

    query = Listing.joins(:pet)
    query = query.where('pets.name LIKE ?', sanitize_sql_like(params[:name]) + '%') if params.include?(:name)

    params.except(:name).each do |k, v|
      sub_query = { k => v }
      sub_query.transform_keys!(&:to_sym)
      query = query.joins(:pet).where(pets: sub_query)
      # query = query.joins(:pet).where(sanitize_sql_hash_for_assignment(sub_query, self))
    end
    query
  end

  scope :random_sample, -> (num = nil) { order('RANDOM()').take(num || 10) }
end

app/models/listings/listing_creation.rb
module Listings
  class ListingCreation
    def self.call(session)
      new(session).call
    end

    def initialize(session)
      @session = session
    end

    def call
      listing = Current.current_user.listings.build(listing_params)
      listing.build_pet(pet_params)
      listing
    end

    private

    def listing_params
      @session[:listing_info]
    end

    def pet_params
      @session[:petinfo]
    end
  end
end

app/models/listings/listing_report.rb
module Listings
  class ListingReport
    include ActiveModel::Model
    # include ActiveModel::Validations

    attr_accessor :listing_type, :lost_found_date, :address, :crossroads, :pet_description, :comment

    validates :listing_type, :lost_found_date, :address, :crossroads, :pet_description, :comment, presence: true
  end
end

app/models/listings/pet_info.rb
module Listings
  class PetInfo
    include ActiveModel::Model

    attr_accessor :image, :name, :species, :gender, :size, :breed, :color, :coat, :age, :height, :weight, :microchip,
                  :collar, :description

    validates :name, :species, :gender, :size, :color, :description, presence: true
  end
end

app/controllers/listings/base_controller.rb
module Listings
  class BaseController < ApplicationController

  end
end

app/controllers/listings/completed_controller.rb
  module Listings
    class CompletedController < BaseController

      def show
        @listing = Listing.find(params[:id])
      end

    end
  end

app/controllers/listings/pets_controller.rb
# step 2

# module Wizards
module Listings
  class PetsController < BaseController
    skip_before_action :authenticate_user!

    def new
      @petinfo = PetInfo.new(session[:petinfo])
    end

    def show
      @pet = Pet.find(params[:id])
    end

    def create
      @petinfo = PetInfo.new(petinfo_params)
      set_session_data
      if @petinfo.valid?
        listing = ListingCreation.call(session)
        if listing.save
          session.delete(:listing_info)
          session.delete(:petinfo)
          redirect_to listings_completed_path(listing)
        end
      else
        render :new
      end
    end

    protected

    def petinfo_params
      params
        .require(:listings_pet_info)
        .permit(:image, :name, :species, :gender, :size, :breed, :color, :coat, :age, :height, :weight, :microchip, :collar, :description)
    end

    def set_session_data
      session[:petinfo] = {
        image: @petinfo.image,
        name: @petinfo.name,
        species: @petinfo.species,
        gender: @petinfo.gender,
        size: @petinfo.size,
        breed: @petinfo.breed,
        color: @petinfo.color,
        coat: @petinfo.coat,
        age: @petinfo.age,
        height: @petinfo.height,
        weight: @petinfo.weight,
        microchip: @petinfo.microchip,
        collar: @petinfo.collar,
        description: @petinfo.description
      }
    end
  end
end
# end

app/controllers/listings/posts_controller.rb
module Listings
  class PostsController < BaseController
    include Pagy::Backend
    skip_before_action :authenticate_user!
    before_action :listing_params

    def index
      @pagy, @listings_posts = pagy(Listing.search(listing_params), items: 9)
    end

    protected

    def listing_params
      params.permit(:name, :species, :breed).reject! { |_k, v| v.blank? }
    end
  end
end

app/controllers/listings/reports_controller.rb
# step 1

  module Listings
    class ReportsController < BaseController

      def index
        @listings = Listing.all.includes(:pet).order(created_at: :desc)
      end

      def new
        @listing_report = ListingReport.new(session[:listing_info])
      end

      def show
        @listing = Listing.find_by(id: params[:id])
      end

      def create
        @listing_report = ListingReport.new(listing_report_params)
        if @listing_report.valid?
          set_session_data
          redirect_to new_listings_pet_path
        else
          render :new
        end
      end

      private

      def listing_report_params
        params.require(:listings_listing_report).permit(
            :listing_type,
            :lost_found_date,
            :address,
            :crossroads,
            :pet_description,
            :comment
          )
      end

      def set_session_data
        session[:listing_info] = {
          listing_type: @listing_report.listing_type,
          lost_found_date: @listing_report.lost_found_date,
          address: @listing_report.address,
          crossroads: @listing_report.crossroads,
          pet_description: @listing_report.pet_description,
          comment: @listing_report.comment,
        }
      end
    end

  end

app/controllers/wizards/listings/completed_controller.rb
module Wizards
  module Listings
    class CompletedController < ApplicationController

      def show

      end

    end
  end
end

app/controllers/wizards/listings/pets_controller.rb
# step 2

module Wizards
  module Listings
    class PetsController < ApplicationController

      def new
        @pet_info = PetInfo.new
      end

      def create
        @pet_info = PetInfo.new(pet_info_params)
        if @pet_info.valid?
          redirect_to wizards_listings_pets_path
        else
          render :new
        end
      end



      protected

      def pet_info_params
        params
          .require(:pet)
          .permit(:name,:species,:gender,:size,:breed,:color,:coat,:age,:height,:weight,:microchip,:collar,:description)
      end

      def set_session_data
        sesstion[:petinfo] = {
          name: @pet_info.name,
          species: @pet_info.species,
          gender: @pet_info.gender,
          size: @pet_info.size,
          breed: @pet_info.breed,
          color: @pet_info.color,
          coat: @pet_info.coat,
          age: @pet_info.age,
          height: @pet_info.height,
          weight: @pet_info.weight,
          microchip: @pet_info.microchip,
          collar: @pet_info.collar,
          descriptio: @pet_info.descriptio,
        }
      end

    end
  end
end

app/controllers/wizards/listings/reports_controller.rb
# step 1

module Wizards
  module Listings
    class ReportsController < ApplicationController

      def new
        @listing_report = ListingReport.new
      end

      def create
        @listing_report = ListingReport.new(listing_report_params)
        if @listing_report.valid?
          # listing_report_params.to_h
          set_session_data
          redirect_to new_wizards_listings_pet_path
        else
          render :new
        end
      end

      private

      def listing_report_params
        params.require(:wizards_listing_report).permit(
            :listing_type,
            :lost_found_date,
            :address,
            :crossroads,
            :pet_description,
            :comment
          )
      end

      def set_session_data
        session[:listing_report] = {
          listing_type: @listing_report.listing_type,
          lost_found_date: @listing_report.lost_found_date,
          address: @listing_report.address,
          crossroads: @listing_report.crossroads,
          pet_description: @listing_report.pet_description,
          comment: @listing_report.comment
        }
      end
    end

  end
end

app/helpers/listing_helper.rb
module ListingHelper
  include Pagy::Frontend

  def listing_type_options
    Listing.listing_types.map { |k, _v| [k.capitalize, k] }
  end
end

app/helpers/listings/pet_helper.rb
module Listings::PetHelper
  def pet_input_selector(attribute)
    Pet.public_send(attribute.to_s.pluralize.to_sym).map { |k, _v| [k.capitalize, k] }
  end

  def pet_constrains
    {
      name: { presence: { allowEmpty: false, message: "^Pet name can't be blank" } },
      # species: { inclusion: { within: Pet.species.keys, message: '^Species is no not included in the list' } },
      species: { presence: { allowEmpty: false, message: "^Species name can't be blank" } },
      gender: { presence: { allowEmpty: false, message: "^Gender name can't be blank" } },
      size: { presence: { allowEmpty: false, message: "^Size name can't be blank" } },
      color: { presence: { allowEmpty: false, message: "^Color name can't be blank" } },
      description: { presence: { allowEmpty: false, message: "^Description can't be blank" } }
    }
  end
end

app/helpers/listings/posts_helper.rb
module Listings::PostsHelper
end

app/helpers/listings/report_helper.rb
module Listings::ReportHelper
  def report_constrains
    {
      address: { presence: { allowEmpty: false, message: "^Address can't be blank" } },
      crossroads: { presence: { allowEmpty: false, message: "^Nearest Cross Road can't be blank" } },
      pet_description: {
        presence: { allowEmpty: false, message: "^Pet Description can't be blank" },
        length: { minimum: 5, maximum: 128, message: '^Pet Description must be between 5 and 128 characters' }
      },
      comment: { presence: { allowEmpty: false, message: "^Comment  can't be blank" },
                 length: { minimum: 5, maximum: 128, message: '^Comment must be between 5 and 128 characters' } }
    }
  end
end

app/views/listings/reports/_contact.html.erb
	
<div class="row mb-3">
	<div class="col-3 text-end">
		<i class="fa-solid fa-dog fs-3 text-orange" ></i>
	</div>
	<div class="col-9 text-start">
		<div class="media contact-info">
			<div class="media-body">
				<h5>Listing Report</h5>
				<p>Report a new lost or found/stray pet. Please do not add the same pet more than once</p>
			</div>
		</div>
	</div>
</div>
<div class="row mb-3">
	<div class="col-3 text-end">
		<i class="fa-solid fa-hands-holding-child fs-3 text-orange"></i>
	</div>
	<div class="col-9 text-start">
		<div class="media contact-info">
			<div class="media-body">
				<h5>Pet Care</h5>
				<p>Let us take care of the rest so you can have some peace of mind that you are doing all that you can to bring your pet home safely</p>
			</div>
		</div>
	</div>
</div>
<div class="row mb-3">
	<div class="col-3 text-end">
		<i class="fa-solid fa-users fs-3 text-orange"></i>
	</div>
	<div class="col-9 text-start">
		<div class="media contact-info">
			<div class="media-body">
				<h5>Buttonwood, California.</h5>
				<p>Reach out to us with any questions you may still have. We're here to help and do what we can to reunite you with your lost dog or cat</p>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-3 text-end">
		<i class="fa-solid fa-users fs-3 text-orange"></i>
	</div>
	<div class="col-9 text-start">
		<div class="media contact-info">
			<div class="media-body">
				<h5>Submit a Report</h5>
				<p>Fill out our grant-report form to show how your grant has helped the pets in your care.</p>
			</div>
		</div>
	</div>
</div>

app/views/listings/reports/_form.html.erb
<div class="row text-start">
	<%=
        form_with model: @listing_report,
        url: listings_reports_path,
        class: 'listing-report needs-validation',
        data: {
            controller: "validate",
            validate_target: "form",
            validate_status_value: true
            } do |form|
    %>
	<div class="row text-start">
		<div class="col-md-8 col-lg-8 col-sm-12">
			<%= content_tag :div, nil, { class: 'form-group mb-3'} do %>
				<%= form.label  :listing_type, { class: 'form-label' }  %>
				<%= form.select :listing_type,
                    options_for_select(listing_type_options),
                    {},
                    { :class => 'form-select', auto_focus: true }
                %>
			<% end %>
		</div>
		<div class="col-md-4 col-lg-4 col-sm-12">
			<%= content_tag :div, nil, { class: 'form-group mb-3'} do %>
				<%= form.label :date_last_seen, { class: 'form-label'} %>
				<%= form.date_field :lost_found_date, {value: Time.now.strftime("%Y-%m-%d"), class: 'form-control'} %>
				<%= feedback_for? @listing_report, :lost_found_date %>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 col-lg-12 col-sm-12">
			<%= content_tag :div, nil, { class: 'form-group mb-3'} do %>
				<%= form.label :Last_seed_Address, { class: 'form-group mb-0'} %>
				<%= form.text_field :address, {
                    class: 'form-control box-shadow',
                    data: {
                        validate_target: 'input',
                        action: "change->validate#handleChange",
                        validate_index_param: 1,
                        constrain: report_constrains[:address]
                        }
                    }
                %>
				<%= feedback_for? @listing_report, :address %>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 col-lg-12 col-sm-12">
			<%= content_tag :div, nil, { class: 'form-group mb-3'} do %>
				<%= form.label 'Nearest cross streets, landmark or location', { class: 'form-group mb-0'} %>
				<%= form.text_field :crossroads, { class: 'form-control',
                    data: {
                        validate_target: 'input',
                        action: "change->validate#handleChange",
                        constrain: report_constrains[:crossroads]
                        }
                    }
                %>
				<%= feedback_for? @listing_report, :crossroads %>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 col-lg-12 col-sm-12">
			<%= content_tag :div, nil, { class: 'form-group mb-3'} do %>
				<%= form.label :pet_description, { class: 'form-group mb-0'} %>
				<%= form.text_area :pet_description, { class: 'form-control', rows: 5,
                    data: {
                        validate_target: 'input',
                        action: "change->validate#handleChange",
                        constrain: report_constrains[:pet_description]
                        }
                    }
                %>
				<%= feedback_for? @listing_report, :pet_description %>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 col-lg-12 col-sm-12">
			<%= content_tag :div, nil, { class: 'form-group mb-3'} do %>
				<%= form.label :comment, { class: 'form-group mb-0'} %>
				<%= form.text_area :comment, { class: 'form-control', rows: 5,
                    data: {
                        validate_target: 'input',
                        action: "change->validate#handleChange",
                        constrain: report_constrains[:comment]
                        }
                    }
                %>
				<%= feedback_for? @listing_report, :comment %>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 col-lg-12 col-sm-12">
			<%= content_tag :div, nil, { class: "form-control text-center border-0" } do %>
				<%= form.submit "Continue", class: "boxed-btn3 border-0", data: { action: "validate#handleForm" } %>
			<% end %>
		</div>
	</div>
<% end %>
</div>

app/views/listings/reports/_form_contact.html.erb
<div class="col-md-4 col-lg-4 py-5 d-flex flex-column justify-content-between">
	<div class="row">
		<div class="col-3 text-end">
			<i class="fa-solid fa-dog font-color"></i>
		</div>
		<div class="col-9 text-start">
			<div class="media contact-info">
				<div class="media-body">
					<h3>Listing Report</h3>
					<p>Report a new lost or found/stray pet. Please do not add the same pet more than once</p>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-3 text-end">
			<i class="fa-solid fa-hands-holding-child font-color"></i>
		</div>
		<div class="col-9 text-start">
			<div class="media contact-info">
				<div class="media-body">
					<h3>Pet Care</h3>
					<p>Let us take care of the rest so you can have some peace of mind that you are doing all that you can to bring your pet home safely</p>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-3 text-end">
			<i class="fa-solid fa-users font-color"></i>
		</div>
		<div class="col-9 text-start">
			<div class="media contact-info">
				<div class="media-body">
					<h3>Buttonwood, California.</h3>
					<p>Reach out to us with any questions you may still have. We're here to help and do what we can to reunite you with your lost dog or cat</p>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/listings/reports/edit.html.erb
<%= turbo_frame_tag "form-wizard" do %>
<%= render 'form', listing_report: @listing_report %>
<% end %>

app/views/listings/reports/index.html.erb
<% content_for(:title, "Listing Report") %>
<%= turbo_frame_tag "Listings"  do %>
	<div class="container mt-4 w-75">
		<div class="row justify-content-md-center">
			<table class="table">
				<thead>
					<th scope="col">Listing Type</th>
					<th scope="col">Created At</th>
					<th scope="col">Pet Name</th>
					<th scope="col">Pet Age</th>
					<th scope="col">Lost & Found Date</th>
					<th scope="col"></th>
				</thead>
				<tbody>
					<% @listings.each do |listing| %>
						<tr>
							<td><%= listing.listing_type %></td>
							<td><%= listing.created_at.strftime("%d %b %y") %></td>
							<td><%= listing.pet.name %></td>
							<td><%= listing.pet.age %></td>
							<td><%= listing.lost_found_date %></td>
							<td>
								<%= link_to listings_report_path(listing), target: :_top do %>
									<i class="bi bi-box-arrow-up-left"></i>
								<% end %>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
		<%= link_to "Report new Listing", new_listings_report_path, {
            data: { turbo_frame: :_top},
            rel: "next",
            class: 'btn btn-light rounded-pill py-2 px-4 text-warning'
        } %>
	</div>
	<%= console %>
<% end %>

app/views/listings/reports/listing_type_radio.html.erb
<%= content_tag :div, nil, { class: 'form-group mb-2'} do %>
    <%= form.label 'listing_type', { class: 'form-check-label'} %>
    <% Listing.listing_types.keys.each do |o| %>
        <%= content_tag :div, nil, { class: 'form-check' } do %>
            <%= form.radio_button :listing_type, o, checked: false, class: 'form-check-input' %>
            <%= content_tag :span, o.capitalize %>
        <% end %>
    <% end %>
<% end %>

app/views/listings/reports/new.html.erb
<% content_for(:title, "Listing Report") %>
<%= turbo_frame_tag "form_wizard", data: {turbo_action: 'advance'} do %>
	<div class="row mx-4">
		<div class="row-12 w-100 my-3">
			<h3 class="card-header text-start">Report Lost & Found</h3>
		</div>
		<div class="col-md-8 col-lg-8 col-sm-12">
			<%= render 'form' %>
		</div>
		<div class="col-md-4 col-lg-4 col-sm-12 d-flex flex-column">
			<%= render 'contact' %>
		</div>
	</div>
<% end %>

app/views/listings/reports/show.html.erb
<%= turbo_frame_tag "listing" do %>
	<div class="container mt-4">
		<div class="row justify-content-md-center">
			<div class="col col-lg-6 col-md-6 col-sm-6">
				<div class="card">
					<div class="pet-image">
						<%= image_tag  @listing.pet.image, {
                                    class: "image-fluid w-100 p-3 rounded-3",
                                    alt: "pet-image",
                                    data: {
                                        image_target: "output",
                                        bs_toggle: "tooltip",
                                        bs_placement: "top",
                                        bs_custom_class: "custom tooltip",
                                        bs_title: "upload your pet image"
                                    }
                                }
                        %>
					</div>
					<div class="card-body">
						<div class="card-title text-center fs-3">
							<%= @listing.pet.name %>
						</div>
						<div class="row align-items-start">
							<div class="col">
								<ul class="list-group list-group-flush">
									<li class="list-group-item px-0 fs-5">
										Listing Type
									</li>
								</ul>
							</div>
							<div class="col">
								<ul class="list-group list-group-flush">
									<li class="list-group-item px-0 fs-5">
										<%= @listing.listing_type %>
									</li>
								</ul>
							</div>
						</div>
						<div class="row align-items-start">
							<div class="col">
								<ul class="list-group list-group-flush">
									<li class="list-group-item px-0 fs-5">
										Pet Species
									</li>
								</ul>
							</div>
							<div class="col">
								<ul class="list-group list-group-flush">
									<li class="list-group-item px-0 fs-5">
										<%= @listing.pet.species %>
									</li>
								</ul>
							</div>
						</div>
						<div class="row align-items-start">
							<div class="col">
								<ul class="list-group list-group-flush">
									<li class="list-group-item px-0 fs-5">
										Pet Size
									</li>
								</ul>
							</div>
							<div class="col">
								<ul class="list-group list-group-flush">
									<li class="list-group-item px-0 fs-5">
										<%= @listing.pet.size %>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<br>
				<%= link_to "back", :back, {
                        data:
                            { turbo_frame: :_top },
                            rel: 'prev',
                            class: 'btn btn-light rounded-pill py-2 px-4 text-warning'
                    } %>
			</div>
		</div>
	</div>
</div>
<% end %>