config/routes.rb
Rails.application.routes.draw do
  namespace :listings do
    resources :reports, only: %i[index show new create]
    resources :pets, only: %i[new create show]
    resources :completed, only: :show
    resources :posts, only: :index
  end

  devise_for :users
  resources :about, only: :index
  resources :contact, only: %i[index create]

  root 'home#index'
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_one :pet, dependent: :destroy

  enum :listing_type, { lost: 0, found: 1 }, default: 0

  def self.search(params)
    return all unless params.present?

    query = Listing.joins(:pet)
    query = query.where('pets.name LIKE ?', sanitize_sql_like(params[:name]) + '%') if params.include?(:name)

    params.except(:name).each do |k, v|
      sub_query = { k => v }
      sub_query.transform_keys!(&:to_sym)
      query = query.joins(:pet).where(pets: sub_query)
      # query = query.joins(:pet).where(sanitize_sql_hash_for_assignment(sub_query, self))
    end
    query
  end

  scope :random_sample, -> (num = nil) { order('RANDOM()').take(num || 10) }
end

app/models/listings/listing_creation.rb
module Listings
  class ListingCreation
    def self.call(session)
      new(session).call
    end

    def initialize(session)
      @session = session
    end

    def call
      listing = Current.current_user.listings.build(listing_params)
      listing.build_pet(pet_params)
      listing
    end

    private

    def listing_params
      @session[:listing_info]
    end

    def pet_params
      @session[:petinfo]
    end
  end
end

app/models/listings/listing_report.rb
module Listings
  class ListingReport
    include ActiveModel::Model
    # include ActiveModel::Validations

    attr_accessor :listing_type, :lost_found_date, :address, :crossroads, :pet_description, :comment

    validates :listing_type, :lost_found_date, :address, :crossroads, :pet_description, :comment, presence: true
  end
end

app/models/listings/pet_info.rb
module Listings
  class PetInfo
    include ActiveModel::Model

    attr_accessor :image, :name, :species, :gender, :size, :breed, :color, :coat, :age, :height, :weight, :microchip,
                  :collar, :description

    validates :name, :species, :gender, :size, :color, :description, presence: true
  end
end

app/controllers/listings/base_controller.rb
module Listings
  class BaseController < ApplicationController

  end
end

app/controllers/listings/completed_controller.rb
  module Listings
    class CompletedController < BaseController

      def show
        @listing = Listing.find(params[:id])
      end

    end
  end

app/controllers/listings/pets_controller.rb
# step 2

# module Wizards
module Listings
  class PetsController < BaseController
    skip_before_action :authenticate_user!

    def new
      @petinfo = PetInfo.new(session[:petinfo])
    end

    def show
      @pet = Pet.find(params[:id])
    end

    def create
      @petinfo = PetInfo.new(petinfo_params)
      set_session_data
      if @petinfo.valid?
        listing = ListingCreation.call(session)
        if listing.save
          session.delete(:listing_info)
          session.delete(:petinfo)
          redirect_to listings_completed_path(listing)
        end
      else
        render :new
      end
    end

    protected

    def petinfo_params
      params
        .require(:listings_pet_info)
        .permit(:image, :name, :species, :gender, :size, :breed, :color, :coat, :age, :height, :weight, :microchip, :collar, :description)
    end

    def set_session_data
      session[:petinfo] = {
        image: @petinfo.image,
        name: @petinfo.name,
        species: @petinfo.species,
        gender: @petinfo.gender,
        size: @petinfo.size,
        breed: @petinfo.breed,
        color: @petinfo.color,
        coat: @petinfo.coat,
        age: @petinfo.age,
        height: @petinfo.height,
        weight: @petinfo.weight,
        microchip: @petinfo.microchip,
        collar: @petinfo.collar,
        description: @petinfo.description
      }
    end
  end
end
# end

app/controllers/listings/posts_controller.rb
module Listings
  class PostsController < BaseController
    include Pagy::Backend
    skip_before_action :authenticate_user!
    before_action :listing_params

    def index
      @pagy, @listings_posts = pagy(Listing.search(listing_params), items: 9)
    end

    protected

    def listing_params
      params.permit(:name, :species, :breed).reject! { |_k, v| v.blank? }
    end
  end
end

app/controllers/listings/reports_controller.rb
# step 1

  module Listings
    class ReportsController < BaseController

      def index
        @listings = Listing.all.includes(:pet).order(created_at: :desc)
      end

      def new
        @listing_report = ListingReport.new(session[:listing_info])
      end

      def show
        @listing = Listing.find_by(id: params[:id])
      end

      def create
        @listing_report = ListingReport.new(listing_report_params)
        if @listing_report.valid?
          set_session_data
          redirect_to new_listings_pet_path
        else
          render :new
        end
      end

      private

      def listing_report_params
        params.require(:listings_listing_report).permit(
            :listing_type,
            :lost_found_date,
            :address,
            :crossroads,
            :pet_description,
            :comment
          )
      end

      def set_session_data
        session[:listing_info] = {
          listing_type: @listing_report.listing_type,
          lost_found_date: @listing_report.lost_found_date,
          address: @listing_report.address,
          crossroads: @listing_report.crossroads,
          pet_description: @listing_report.pet_description,
          comment: @listing_report.comment,
        }
      end
    end

  end

app/controllers/wizards/listings/completed_controller.rb
module Wizards
  module Listings
    class CompletedController < ApplicationController

      def show

      end

    end
  end
end

app/controllers/wizards/listings/pets_controller.rb
# step 2

module Wizards
  module Listings
    class PetsController < ApplicationController

      def new
        @pet_info = PetInfo.new
      end

      def create
        @pet_info = PetInfo.new(pet_info_params)
        if @pet_info.valid?
          redirect_to wizards_listings_pets_path
        else
          render :new
        end
      end



      protected

      def pet_info_params
        params
          .require(:pet)
          .permit(:name,:species,:gender,:size,:breed,:color,:coat,:age,:height,:weight,:microchip,:collar,:description)
      end

      def set_session_data
        sesstion[:petinfo] = {
          name: @pet_info.name,
          species: @pet_info.species,
          gender: @pet_info.gender,
          size: @pet_info.size,
          breed: @pet_info.breed,
          color: @pet_info.color,
          coat: @pet_info.coat,
          age: @pet_info.age,
          height: @pet_info.height,
          weight: @pet_info.weight,
          microchip: @pet_info.microchip,
          collar: @pet_info.collar,
          descriptio: @pet_info.descriptio,
        }
      end

    end
  end
end

app/controllers/wizards/listings/reports_controller.rb
# step 1

module Wizards
  module Listings
    class ReportsController < ApplicationController

      def new
        @listing_report = ListingReport.new
      end

      def create
        @listing_report = ListingReport.new(listing_report_params)
        if @listing_report.valid?
          # listing_report_params.to_h
          set_session_data
          redirect_to new_wizards_listings_pet_path
        else
          render :new
        end
      end

      private

      def listing_report_params
        params.require(:wizards_listing_report).permit(
            :listing_type,
            :lost_found_date,
            :address,
            :crossroads,
            :pet_description,
            :comment
          )
      end

      def set_session_data
        session[:listing_report] = {
          listing_type: @listing_report.listing_type,
          lost_found_date: @listing_report.lost_found_date,
          address: @listing_report.address,
          crossroads: @listing_report.crossroads,
          pet_description: @listing_report.pet_description,
          comment: @listing_report.comment
        }
      end
    end

  end
end

app/helpers/listing_helper.rb
module ListingHelper
  include Pagy::Frontend

  def listing_type_options
    Listing.listing_types.map { |k, _v| [k.capitalize, k] }
  end
end

app/helpers/listings/pet_helper.rb
module Listings::PetHelper
  def pet_input_selector(attribute)
    Pet.public_send(attribute.to_s.pluralize.to_sym).map { |k, _v| [k.capitalize, k] }
  end

  def pet_constrains
    {
      name: { presence: { allowEmpty: false, message: "^Pet name can't be blank" } },
      # species: { inclusion: { within: Pet.species.keys, message: '^Species is no not included in the list' } },
      species: { presence: { allowEmpty: false, message: "^Species name can't be blank" } },
      gender: { presence: { allowEmpty: false, message: "^Gender name can't be blank" } },
      size: { presence: { allowEmpty: false, message: "^Size name can't be blank" } },
      color: { presence: { allowEmpty: false, message: "^Color name can't be blank" } },
      description: { presence: { allowEmpty: false, message: "^Description can't be blank" } }
    }
  end
end

app/helpers/listings/posts_helper.rb
module Listings::PostsHelper
end

app/helpers/listings/report_helper.rb
module Listings::ReportHelper
  def report_constrains
    {
      address: { presence: { allowEmpty: false, message: "^Address can't be blank" } },
      crossroads: { presence: { allowEmpty: false, message: "^Nearest Cross Road can't be blank" } },
      pet_description: {
        presence: { allowEmpty: false, message: "^Pet Description can't be blank" },
        length: { minimum: 5, maximum: 128, message: '^Pet Description must be between 5 and 128 characters' }
      },
      comment: { presence: { allowEmpty: false, message: "^Comment  can't be blank" },
                 length: { minimum: 5, maximum: 128, message: '^Comment must be between 5 and 128 characters' } }
    }
  end
end

app/views/listings/base/_form.html.erb
<div class="container mt-4">
    <div class="row justify-content-md-center">
        <div class="col col-lg-6 col-md-6 col-sm-6">
            <div class="card">
                <div class="card-header text-center">
                    form
                </div>
                <div class="card-body">
                    <%= yield  %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/listings/base/_pet_card.html.erb
<div class="card m-2"  id="card-container">
  <div style="width: 20rem;" id="image-container">
    <!-- .representation(resize_to_fill: [300, 300, gravity: 'north']) -->
    <%= image_tag  listing.pet.image, {
            class: "image-fluid w-100 pt-2 rounded-4 card-img-top", alt: "pet-image",
            data: {
                image_target: "output",
                bs_toggle: "tooltip",
                bs_placement: "top",
                bs_custom_class: "custom tooltip",
                bs_title: "upload your pet image"
            }
        }
        %>
  </div>
  <div class="card-body px-0 pt-3 d-flex flex-column">
    <div class="row mx-2 my-1">
      <div class="col-auto px-0">
        <h3 class="card-title text-start">
          <%= listing.pet.name %>
          <span class="fs-6 fw-light">
            <%= listing.pet.gender.capitalize %>
            <%= listing.pet.species.capitalize %>
          </span>
        </h3>
      </div>
    </div>
    <div class="row mx-2 my-1">
      <div class="col-auto px-0">
        <h4 class="text-start">
          <%= listing.listing_type.capitalize %>
          <span class="fs-6 fw-light">
            <%= listing.lost_found_date.strftime("%d %b %y") %>
          </span>
        </h4>
      </div>
    </div>
    <div class="row mx-2 my-1">
      <div class="col-auto px-0">
        <p class="text-start text-justify">
          <%= listing.address.capitalize %>
        </p>
      </div>
    </div>
    <div class="row mx-2 my-1">
      <div class="col-auto px-0">
        <p class="text-start text-justify">
          <%= listing.pet.description.capitalize.truncate(100) %>
        </p>
      </div>
    </div>
    <div class="row mx-2 my-1">
      <div class="col-auto px-0">
        <p class="text-start fst-italic">
          <i class="bi bi-flag">
            reported <%= time_ago_in_words listing.created_at  %>
          </i>
        </p>
      </div>
    </div>
    <div class="row mx-2 my-1">
      <%= link_to "View Pet", listings_post_path(listing), {
        data: { turbo_frame: :_top },
        rel: 'next',
        class: "btn btn-light rounded-pill px-5 "}
      %>
    </div>
  </div>
</div>