config/routes.rb
Rails.application.routes.draw do
  namespace :listings do
    resources :reports, only: %i[index show new create]
    resources :pets, only: %i[new create show]
    resources :completed, only: :show
    resources :posts, only: :index
  end

  devise_for :users
  resources :about, only: :index
  resources :contact, only: %i[index create]

  root 'home#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  before_action :set_current_user
  before_action do
    ActiveStorage::Current.url_options = { protocol: request.protocol, host: request.host, port: request.port }
  end

  protected

  def set_current_user
    Current.current_user = current_user
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def feedback_for?(object, attribute)
    return nil if object.errors.empty?

    if object.errors.has_key?(attribute)
      return content_tag :div, nil, { class: %w[d-block invalid-feedback] } do
        object.errors.full_messages_for(attribute).to_sentence
      end
    end
    nil
  end

  def inline_error_for(object, attribute)
    html = []
    if object.errors[attribute].any?
      html << object.errors[attribute].each do |msg|
        tag.div(msg, class: 'some class')
      end
    end
    html.join_html_safe
  end


  def input_selector(model, attribute)
    attribute = attribute.is_a?(String) ? attribute.to_sym : attribute
    model.public_send(attribute).map { |k, _| [k.capitalize, k] }
    # model.public_send(attribute.pluralize.to_sym).map { |k, _| [k.capitalize, k] }
  end

  def current_model(object)
    object.class.name.gsub('::', '').underscore
  end
  def model_name
    controller_path.classify
  end
end

app/views/application/_flash.html.erb
<%# if !flash.empty? %>
<div class="flash-errors">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == 'notice' ? 'success' : 'danger' %>" role="alert">
      <%= msg %>
    </div>
  <% end %>
</div>
<%# end %>

app/views/application/_flash_bootstrap.html.erb
<% flash.each do |msg_type, message| %>
	<div class="alert <%= bootstrap_class_for(msg_type) %>">
		<div class="container">
			<button class="close" data-dismiss="alert"><span>×</span></button>
			<%= message %>
		</div>
	</div>
<% end %>

app/views/application/_footer.html.erb
<footer class="footer">
	<div class="footer_top">
		<div class="container">
			<div class="row">
				<div class="col-sm-12 col-md-3 col-lg-3">
					<div class="footer_widget mx-auto">
						<h3 class="footer_title">
							Contact Us
						</h3>
						<ul class="address_line">
							<li>Boula Akladyous</li>
							<li><a href="#">akladyous@gmail.com</a></li>
							<li>Florida, USA</li>
						</ul>
					</div>
				</div>
				<div class="col-sm-12 col-md-3 col-lg-3">
					<div class="footer_widget mx-auto">
						<h3 class="footer_title">
							Our Servces
						</h3>
						<ul class="links">
							<li><a href="#">Pet Insurance</a></li>
							<li><a href="#">Pet surgeries </a></li>
							<li><a href="#">Pet Adoption</a></li>
						</ul>
					</div>
				</div>
				<div class="col-sm-12 col-md-3 col-lg-3">
					<div class="footer_widget mx-auto">
						<h3 class="footer_title">
							Quick Link
						</h3>
						<ul class="links">
							<li><a href="#">About Us</a></li>
							<li><a href="#">Privacy Policy</a></li>
							<li><a href="#">Terms of Service</a></li>
						</ul>
					</div>
				</div>
				<div class="col-sm-12 col-md-3 col-lg-3">
					<div class="footer_widget mx-wuto">
						<p class="address_text">Powerd by Ruby On Rails</p>
						<div class="socail_links">
							<ul>
								<li>
									<a href="#">
										<i class="ti-facebook"></i>
									</a>
								</li>
								<li>
									<a href="#">
										<i class="ti-pinterest"></i>
									</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</footer>

app/views/application/_head.html.erb
<title>
	<%= content_for?(:title) ? yield(:title) : "Pet Finder Application" %>
</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "index", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "style", "data-turbo-track": "reload" %>
<%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

app/views/application/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
	<%= link_to root_path, {'class': 'navbar-brand p-0'} do %>
		<%= image_tag("icons/logo.png", { 'width': 40, 'height': 35, 'alt': 'ruby on rails'}) %>
	<% end %>
	<button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
    >
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<div class="navbar-nav mx-auto py-0">
			<%= link_to "home", root_path, {class: "nav-link", 'aria-current': "page" } %>
			<%= link_to "about", about_index_path, {class: "nav-link", 'aria-current': "page" } %>
			<%= link_to "Testimonials", root_path, {class: "nav-link", 'aria-current': "line" } %>
			<%= link_to "Lost & Found", listings_posts_path, {class: "nav-link", 'aria-current': "line" } %>
			<%= link_to "Report Lost Pet", new_listings_report_path, {class: "nav-link", 'aria-current': "line" } %>
			<%= link_to "contact", contact_index_path, {class: "nav-link", 'aria-current': "line" } %>
		</div>
		<%# <div class="navbar-nav gap-3"> %>
		<%= render 'user_links' %> <%= yield :user_menu %>
		<%# </div> %>
		<button class="btn btn-"></button>
	</div>
</nav>

app/views/application/_notice.html.erb
<% flash.each do |msg_type, message| %>
  <div class="alert <%= bootstrap_class_for(msg_type) %>">
    <div class="container">
      <button class="close" data-dismiss="alert"><span>×</span></button>
      <%= message %>
    </div>
  </div>
<% end %>

app/views/application/_title.html.erb
<div class="page-header page-header-bg">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="bradcam_text text-center">
					<h3 class="text-white">
						<%= yield :title %>
					</h3>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/application/_user_links.html.erb
<% turbo_exempts_page_from_cache %>
<% content_for :user_menu do %>
  <div class="navbar-nav gap-3">
    <% if user_signed_in? %>
      <%= link_to current_user.email, edit_user_registration_path, class: 'current-user' %>
      <%= button_to "Logout", destroy_user_session_path, class: "dropdown-item #{user_signed_in? ? '' : 'disabled'}", method: :delete %>
    <% else %>
      <%= link_to 'Signup', new_user_registration_path, { class: "nav-link"  } %>
      <%= link_to "Login", new_user_session_path, { class: "btn btn-light d-none d-lg-block" } %>
    <% end %>
  </div>
<% end %>